# Generated by Django 3.2.5 on 2021-09-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0004_auto_20210906_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='adress',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Ordonnace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default=None, max_length=100)),
                ('note', models.TextField(default=None)),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnaces', to=settings.AUTH_USER_MODEL)),
                ('fiche', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordonnaces', to='workplace.fiche')),
            ],
        ),
    ]
