# Generated by Django 3.2.5 on 2021-09-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0006_auto_20210915_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='analyses',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='analyse',
            name='results',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='bonanalyse',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='conclusion',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='facturegrid',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='poid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fiche',
            name='temperature',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ordonnace',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='prelevement',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='soin',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
