# Generated by Django 3.2.5 on 2021-09-20 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workplace', '0007_auto_20210920_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='note',
        ),
        migrations.CreateModel(
            name='WorkplaceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(default=None, max_length=100)),
                ('data', models.JSONField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workplace_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
