# Generated by Django 3.2.5 on 2021-09-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workplace', '0002_auto_20210904_2338'),
        ('users', '0002_alter_patient_editor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
