# Generated by Django 3.2.5 on 2021-09-15 12:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
