# Generated by Django 3.2.5 on 2021-07-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptextmessage',
            old_name='form',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='simpletextmessage',
            old_name='form',
            new_name='author',
        ),
    ]
