# Generated by Django 3.2.5 on 2021-07-29 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210729_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletextmessage',
            name='message_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
