# Generated by Django 3.2.5 on 2021-07-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_simpletextmessage_message_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptextmessage',
            name='message_code',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
