# Generated by Django 3.2.5 on 2021-07-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_simpletextmessage_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simpletextmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
