# Generated by Django 3.2.5 on 2021-08-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210826_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiche',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
