# Generated by Django 3.2.5 on 2021-09-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fiche_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fiche',
        ),
    ]
